### ISSUE TITLE
RangeError: offset is out of bounds

### ISSUE THREAD

**Issue by ItaiCovver** [mattdesl/lcms-wasm#1]
While running `node test/cmyk.js` after following the "Build from source" section no matter which "CMYK" profile I try to import from I get `RangeError: offset is out of bounds`

Here are some that I tried.

https://www.color.org/registry/PSOcoated_v3.xalter
https://www.color.org/exchange_space.xalter
https://www.color.org/registry/SWOP2006_Coated3v2.xalter

`node test/lab.js` works fine though and importing the sRGB profile from [here](https://www.color.org/srgbprofiles.xalter#v2) works fine. Only the "CMYK" profile errors

A really small ICC profile that I found [here](https://github.com/saucecontrol/Compact-ICC-Profiles?tab=readme-ov-file#cmyk) seems to work. Why can't this package import the normal ICC profiles?

**Comment by mattdesl** [comment]
That’s odd. I’ll have a look this week and see if I can sort it out.

**Comment by ItaiCovver** [comment]
I'm running Node `v18.16.0` on an ARM Macbook pro if that has anything to do with it

**Comment by mattdesl** [comment]
Should be fixed in https://github.com/mattdesl/lcms-wasm/commit/8698e9d8691ce49dcb5f4d264942b923b0e1df64. Thanks!
