### ISSUE TITLE
‎cmsCloseProfile calls wrong function

### ISSUE THREAD

**Issue by pcram-techcyte** [mattdesl/lcms-wasm#2]
cmsCloseProfile doesn't work - it's wired up to cmsCreate_sRGBProfile by mistake.

**Comment by pcram-techcyte** [comment]
@mattdesl I've started using lcms-wasm (thank you!!) and I ran into a few small issues like this.  Are you interested in pull requests to fix them?  Do you want one PR per issue, or would you prefer a single PR that has all the fixes together?

**Comment by mattdesl** [comment]
Hey @pcram-techcyte yes sure I'll accept a PR for this! Either is fine, typically separate PRs is best if that's OK.
